"\\language": cpp
matrix:
  include:
  - os: linux
    addons:
      apt:
        packages:
        - gfortran
  - os: osx
    osx_image: xcode10
    env: OSX=10.13
    compiler: clang
  - os: osx
    osx_image: xcode9.2
    env: OSX=10.12
    compiler: clang
  - os: osx
    osx_image: xcode8
    env: OSX=10.11
    compiler: clang
  allow_failures:
  - os: osx
before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  export PLATFORM=osx$OSX-x86_64-clang`clang
  -dumpversion`; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install bash gcc; brew
  link --overwrite gcc; gfortran --version; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PLATFORM=linux-x86_64-gcc`gcc
  -dumpversion`; fi
- git clone https://github.com/coin-or/coinbrew COIN
- cd COIN
- export PROJECT=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 2`
- bash ./coinbrew fetch --no-prompt $PROJECT > /dev/null
script:
- bash ./coinbrew build --no-prompt $PROJECT --enable-static --disable-shared --verbosity 2 --test
